// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArjy8GB27h5yavKjxaHv98N24KcXeURzo',
    appId: '1:812813027200:web:b3fc5d2d98a6f533b02365',
    messagingSenderId: '812813027200',
    projectId: 'fir-project1-dd774',
    authDomain: 'fir-project1-dd774.firebaseapp.com',
    storageBucket: 'fir-project1-dd774.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGxqhTvA-raycUESMEgI7KkgZHnniprS0',
    appId: '1:812813027200:android:67f39be9e29da40fb02365',
    messagingSenderId: '812813027200',
    projectId: 'fir-project1-dd774',
    storageBucket: 'fir-project1-dd774.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpqu8-jxIi6MxQDk5R8UBHwxLq7TqbtEI',
    appId: '1:812813027200:ios:41f9327d920fc26eb02365',
    messagingSenderId: '812813027200',
    projectId: 'fir-project1-dd774',
    storageBucket: 'fir-project1-dd774.appspot.com',
    androidClientId: '812813027200-g9mon1l8vp9krqpdrtf5igcteoqabarv.apps.googleusercontent.com',
    iosClientId: '812813027200-mb5kgovdi8nkfhmcda5krdafli70ghpa.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );
}
